name: pull request

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: 11
      - uses: gradle/actions/wrapper-validation@v4
      - name: Build with Gradle
        run: ./gradlew build
      - name: Archive test result
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: Jfrog-test-report
          path: ./services/build/reports/tests/test/
